# Generated by Django 6.0.7 on 2026-10-06 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genre', models.CharField(max_length=50)),
                ('song_priority', models.CharField(max_length=50)),
                ('preferred_mood', models.CharField(max_length=50)),
                ('listening_context', models.CharField(max_length=50)),
                ('playlist_preference', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
