"""Spotify Web API helpers.

- app token (client_credentials) for catalogue lookups (album art)
- OAuth authorize / code exchange / refresh for user actions
- REST helpers for the playback + playlist endpoints
"""

from datetime import timedelta
from urllib.parse import urlencode

import requests
from django.conf import settings
from django.utils import timezone

AUTH_BASE = "https://accounts.spotify.com"
API_BASE = "https://api.spotify.com/v1"
TIMEOUT = 10

_app_token = {"token": None, "expires_at": 0.0}


def _client_auth():
    return requests.auth.HTTPBasicAuth(
        settings.SPOTIFY_CLIENT_ID, settings.SPOTIFY_CLIENT_SECRET
    )


def app_token():
    """Application access token (no user), cached per process."""
    now = timezone.now()
    if _app_token["token"] and _app_token["expires_at"] > now:
        return _app_token["token"]
    response = requests.post(
        f"{AUTH_BASE}/api/token",
        auth=_client_auth(),
        data={"grant_type": "client_credentials"},
        timeout=TIMEOUT,
    )
    response.raise_for_status()
    payload = response.json()
    _app_token["token"] = payload["access_token"]
    _app_token["expires_at"] = now + timedelta(seconds=payload["expires_in"])
    return _app_token["token"]


def authorize_url(state: str) -> str:
    return AUTH_BASE + "/authorize?" + urlencode({
        "client_id": settings.SPOTIFY_CLIENT_ID,
        "response_type": "code",
        "redirect_uri": settings.SPOTIFY_REDIRECT_URI,
        "scope": settings.SPOTIFY_SCOPES,
        "state": state,
    })


def exchange_code(code: str) -> dict:
    response = requests.post(
        f"{AUTH_BASE}/api/token",
        auth=_client_auth(),
        data={
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": settings.SPOTIFY_REDIRECT_URI,
        },
        timeout=TIMEOUT,
    )
    response.raise_for_status()
    return response.json()


def _refresh(refresh_token: str) -> dict:
    response = requests.post(
        f"{AUTH_BASE}/api/token",
        auth=_client_auth(),
        data={"grant_type": "refresh_token", "refresh_token": refresh_token},
        timeout=TIMEOUT,
    )
    response.raise_for_status()
    return response.json()


def ensure_fresh(token_row) -> str:
    """Return a valid access token, refreshing the row when expiring."""
    if timezone.now() < token_row.expires_at - timedelta(seconds=60):
        return token_row.access_token
    payload = _refresh(token_row.refresh_token)
    token_row.access_token = payload["access_token"]
    token_row.expires_at = timezone.now() + timedelta(
        seconds=payload.get("expires_in", 3600)
    )
    if payload.get("refresh_token"):
        token_row.refresh_token = payload["refresh_token"]
    token_row.save(update_fields=["access_token", "expires_at", "refresh_token"])
    return token_row.access_token


def _request(method, url, token, **kwargs):
    headers = kwargs.pop("headers", {})
    headers.setdefault("Authorization", f"Bearer {token}")
    response = requests.request(
        method, url, headers=headers, timeout=TIMEOUT, **kwargs
    )
    return response


def user_get(token_row, path) -> dict:
    response = _request("GET", f"{API_BASE}{path}", ensure_fresh(token_row))
    response.raise_for_status()
    return response.json()


def fetch_tracks(track_ids) -> dict:
    """Batch lookup (<=50 ids) with the app token.

    Returns {track_id: image_url_or_empty} for ids that still exist;
    removed/bogus ids are simply absent from the mapping.
    """
    if not track_ids:
        return {}
    response = _request(
        "GET",
        f"{API_BASE}/tracks?ids={','.join(track_ids)}",
        app_token(),
    )
    response.raise_for_status()
    mapping = {}
    for track in response.json():
        if not track:
            continue
        images = track.get("album", {}).get("images") or []
        # prefer the 300px cover, fall back to whatever exists
        image = next(
            (i["url"] for i in images if i.get("height") == 300),
            images[0]["url"] if images else "",
        )
        mapping[track["id"]] = image
    return mapping


def create_playlist(token_row, name: str, uris: list, public: bool = False) -> str:
    """Create a playlist for the user, add the tracks, return its URL."""
    token = ensure_fresh(token_row)
    response = _request(
        "POST",
        f"{API_BASE}/users/{token_row.spotify_user_id}/playlists",
        token,
        json={
            "name": name,
            "public": public,
            "description": "Generated by the Music Recommendation app",
        },
    )
    response.raise_for_status()
    playlist = response.json()

    if uris:  # 100 uri cap per call; our lists are 20
        response = _request(
            "POST",
            f"{API_BASE}/playlists/{playlist['id']}/tracks",
            token,
            json={"uris": uris},
        )
        response.raise_for_status()

    return playlist["external_urls"]["spotify"]
