# Generated by Django 6.0.7 on 2026-10-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('track_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, default='')),
                ('found', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'spotify_tracks',
            },
        ),
    ]
